### ISSUE TITLE
Search for: textbox does not support right-click or Ctrl+A

### ISSUE THREAD

**Issue by norberturkiewicz** [aplteam/Fire#10]
There is so easy way to do a standard Select All vis keyboard or mouse.  This is a problem with really long expressions that I'd like to copy.

Edit->Select All doesn't seem to do anything.

Fire version 6.6.3.5

**Comment by aplteam** [comment]
Originally Ctrl+A had an effect only when there was a hit list: in that case all rows got selected.

It seems you want it to work on the "Search for" field as well.

The menu command "Select all" cannot work out you attention. I have therefore removed the menu command from the "Edit" command and instead support now Ctrl+A in both the hit list and and the Search for" edit control. That should give you what you want, right?

**Comment by norberturkiewicz** [comment]
I’d expect text and edit boxes to have the standard or close to, Windows behavior and context menus.

**Comment by aplteam** [comment]
Implemented
