### ISSUE TITLE
Fire does not reposition to existing monitor after being closed on nonexistent monitor

### ISSUE THREAD

**Issue by norberturkiewicz** [aplteam/Fire#13]
If I close fire while its position is on monitor B and unplug the monitor, fire will not reposition on the main monitor.

This fixes the issue

```
 n←CreateGUI debugFlag;isAv;posn;size;IsPosnAvailable
⍝
 n←##.CreateGuiRefContainer
 n←CreateIcon n
 n←CreateMainForm debugFlag n
 n←CreateHiddenButtons n
 n←CreateFind n
 n←CreateWhereToLook n
 n←CreateTabs n
 n←CreateTab1Children n
 n←CreateTab2Children n
 n←CreatePushButtons n
 n←CreateCheckBoxes n
 n←CreateHitList n
 n←SetStateAndActive n
 n←CheckStartButton n

 IsPosnAvailable←{
 ⍝ check if coords are actually available to be displayed on
     ⎕USING←'System.Windows.Forms,System.Windows.Forms.dll' 'System.Drawing,System.Drawing.dll'
     (y x)(h w)←⍵
     pt←⎕NEW Point(x y)
     screens←Screen.AllScreens
     contains←screens.Bounds.Contains pt
     ∨/contains
 }


 :Trap 0
     :If IsPosnAvailable ##.G.(Posn Size)
         posn←##.G.Posn
         size←##.G.Size
     :EndIf
 :EndTrap

 n.Form.Posn←posn
 n.Form.Size←size
⍝Done
```

**Comment by norberturkiewicz** [comment]
My argument is that Fire GUI is Windows only and a restart or needing to know command switches aren’t really a good solution to a bug.

**Comment by aplteam** [comment]
Well, whether it will stay "Windows only" is something I am not so sure about.

Also, from my point of view it's not a bug: when you move some window to a monitor and then unplug that monitor, well, ….

Paul?

**Comment by aplteam** [comment]
I've changed Fire so that when `]Fire` is issued while the Form is both in existence and visible the Posn is reset to `⍬ ⍬`. That way you still have to restart, but not your APL session but just Fire.


Comments are welcome.
