### ISSUE TITLE
fire does not find ReadMe.html if User command path is [HOME]\MyUCMDs

### ISSUE THREAD

**Issue by dyavc** [aplteam/Fire#39]
fire does not find ReadMe.html if User command path is [HOME]\MyUCMDs

I installed fire 9.6

I start Dyalog 18.2 64-bit Unicode

]fire
* Command Execution Failed: Cannot find HTML documents
⍝  using ]udebug on to examine the failure:

v
 [HOME]\MyUCMDs  [SALT]\spice 

     :For thisPath :In v

)si
⎕SE._Fire.Fire.FindFireReadMe[27]*
⎕SE._Fire.Fire.Run[27]
⎕SE.input.c.Fire_UC.LoadFire[18]
⎕SE.input.c.Fire_UC.Run[26]
⍎
⎕SE.SALTUtils.CallUserCode[0]
⎕SE.UCMD[2]

After installing, I do not have a Fire key in APLTree.  I work around this issue by creating a Fire key and a string value HelpFileFolder as I can see in the code.
HKCU\Software\APLTree\Fire\HelpFileFolder

**Comment by aplteam** [comment]
I have created a pre-release 9.6.1 with a fix. Please give it a try and report back.

Tx

**Comment by dyavc** [comment]
Thanks Kai.  I have tried the 9.6.1 fix.  ]fire now starts the GUI fine.

If I do Help->"View ReadMe",  it opens a Windows explorer window on the MyUCMDs\Fire directory.  I expected the ReadMe.html file to be opened.

I get "Could not find the document" for Help->View "Useful RegExes" and View "Release Notes".
Those files do exist in the MyUCMDs\Fire directory.

**Comment by aplteam** [comment]
Hmmm. Where is your `HOME` coming from? 

I have specified `HOME` on the command line as `HOME="C:\Users\kai\Documents"`, and everything works as it should.

I have produced a second beta that puts the path for the "Readme" and the Release notes on display. Please take screenshots and send them to me.

**Comment by dyavc** [comment]
Sure, if I specify a HOME parameter like that it works as it should.

I do not have a HOME environment variable or parameter set.  I will email you the screenshots.
