### ISSUE TITLE
Pressing down arrow wile typing "Search For" phrase empties current letters

### ISSUE THREAD

**Issue by norberturkiewicz** [aplteam/Fire#4]
When I'm trying a search phrase and mistakenly hit down arrow, the search phrase is deleted.

The search phrase dropdown is empty on my system.

**Comment by aplteam** [comment]
This is by design, though it should **_not_** do this when the list is empty.

**Comment by aplteam** [comment]
It's actually Windows behaviour, and it would need a major effort to program around this. Just don't hit <arrow-down>...

**Comment by aplteam** [comment]
But Fire could ignore the <CursorDown> key in case that list is empty! That's what I am gonna do.

**Comment by aplteam** [comment]
Fixed.
