### ISSUE TITLE
Clicking How to Install link in the doc produces html instead of a rendered page.

### ISSUE THREAD

**Issue by norberturkiewicz** [aplteam/Fire#8]
Bug or feature?

https://github.com/aplteam/Fire/tree/master/Docs

![image](https://user-images.githubusercontent.com/5807754/49176985-b61abf80-f311-11e8-8944-07327f52c94f.png)

![image](https://user-images.githubusercontent.com/5807754/49177031-cdf24380-f311-11e8-8e83-44b665b77b92.png)

**Comment by aplteam** [comment]
Feature.

More precisely: GitHub feature. When you click on an HTML file GitHub shows the code.

When you download a Fire release and then click on that file then it renders fine in your default browser.

**Comment by norberturkiewicz** [comment]
@aplteam should the ReadMe.md reference howtoinstall.md instead of howtoinstall.html?

**Comment by aplteam** [comment]
Why? The markdown is the source format, but one wants to looks at the HTML, don't you think?

**Comment by norberturkiewicz** [comment]
I think it would be more useful if it went to the same file type (consistency) and rendered properly.  The ReadMe.html can point to howtointsall.html and readme.md can point to howtoinstall.md.  The browser will know what to do with the html and github will nicely show the formatted md.
